version: "3.5"
services:
  abricate:
    image: gamboa/biopipe:latest
    volumes:
      - ./output/abricate:/output
      - ./fasta:/fasta
      - ./database:/database
    entrypoint: /bin/bash -c "source activate abricate; bash"
  platon:
    image: gamboa/biopipe:latest
    volumes:
      - ./output/platon:/output
      - ./fasta:/fasta
      - ./database:/database
    entrypoint: /bin/bash -c "source activate platon; bash"
  viralVerify:
    image: gamboa/biopipe:latest
    volumes:
      - ./output/viralVerify:/output
      - ./fasta:/fasta
      - ./database:/database
    entrypoint: /bin/bash -c "source activate viralVerify; bash"
  integron:
    image: gempasteur/integron_finder:2.0rc10
    volumes: 
      - ./output/integron:/output
      - ./fasta:/fasta
    entrypoint: /bin/bash
  unicycler:
    image: gamboa/unicycler:0.5.0
    volumes: 
      - ./output/unicycler:/output
      - ./fasta:/fasta
    entrypoint: unicycler
  mobsuite:
    image: kbessonov/mob_suite:3.0.3
    volumes: 
      - ./output/mobsuite:/output
      - ./fasta:/fasta